
#是否在每次启动时询问语言设置
ask_language_each_start = false

#使用的壁纸路径与对应预设配色文件路径
preset_palette = ~/图片/wallpaper/Image_1778749738312_51.jpg = ~/.config/noctalia/palettes/ZEKniri-preset2.json
preset_palette = ~/图片/wallpaper/Image_1787794163602_662.jpg = ~/.config/noctalia/palettes/ZEKniri-preset.json

#每张壁纸单独的 waybar 配色文件（可多行：壁纸文件 = css 文件)
#waybar_colors = ~/图片/wallpaper/foo.jpg = ~/.config/waybar/colors/foo.css
#waybar_colors = ~/图片/wallpaper/bar.jpg = ~/.config/waybar/colors/bar.css

#日志输出路径
log_path = ~/.local/state/ZEKniri/install.log

#noctalia模式使用哪个取色器
noctalia_scheme_source = wallpaper
noctalia_scheme_name = soft
