
#是否在每次启动时询问语言设置
ask_language_each_start = false

#使用的壁纸路径与对应预设配色文件路径
#wallpaper_dir = ~/图片/wallpaper
#preset_palette = ~/.config/noctalia/palettes/ZEKniri-preset2.json
wallpaper_palette = ~/图片/wallpaper/Image_1778749738312_51.jpg = ~/.config/noctalia/palettes/ZEKniri-preset.json
wallpaper_palette = ~/图片/wallpaper/DD9B0366650E72DBAB0D3775D7568940.jpg = ~/.config/noctalia/palettes/ZEKniri-preset2.json

#日志输出路径
log_path = ~/.local/state/ZEKniri/install.log

#noctalia模式使用哪个取色器
noctalia_scheme_source = wallpaper
noctalia_scheme_name = soft
